### ISSUE TITLE
LIST ENGINES lists every engine twice

### ISSUE THREAD

**Issue by evg-zhabotinsky** [KSP-KOS/KOS#1026]
Running KSP 1.0.2 x64 on Linux.
kOS 0.17.2, clean install, no other mods.

LIST ENGINES lists every engine twice.
Also, MAXTHRUST and AVAILABLETHRUST are exactly twice their proper (vacuum) values.

For whatever reason, I suspect these two are the same problem.

**Comment by ianjirka** [comment]
FWIW, I cannot repro this on 32-bit Windows

**Comment by abenkovskii** [comment]
1. Screenshoot and .craft file please

**Comment by erendrake** [comment]
I believe this is already fixed in the next release. ☺

**Comment by evg-zhabotinsky** [comment]
.craft - any in my case. It seems to be related to engine itself.

Test screenshot:
[screenshot from 2015-05-19 13 58 44](https://cloud.githubusercontent.com/assets/6692701/7701431/b6da4b14-fe2f-11e4-8319-5559b7302cac.png)
When list of engines is stored in variable, the 2 lines per engine still end up as one. (Because they are identical?)

Multiple engines:
[screenshot from 2015-05-19 14 20 08](https://cloud.githubusercontent.com/assets/6692701/7701673/366fd676-fe32-11e4-8e82-e180c63319cd.png)
I launched that second craft to show multiple engines at once, but then noticed that LV-T30 is fine. It is listed only once and added to total MAXTHRUST only once. It is also listed as ModuleEngines, not ModuleEnginesFX.

Thus the next test: all 26 stock engines at once.
[screenshot from 2015-05-19 15 26 47](https://cloud.githubusercontent.com/assets/6692701/7702898/15af1ae6-fe3c-11e4-80f0-e3cb7872227d.png)
(Jeb looks a bit frightened :)

You see: all ModuleEngines are listed once, all ModuleEnginesFX are listed twice.

Also, when I print :ALLMODULES, i see either ModuleEngines, or ModuleEnginesFX, but not both.

------------------

Side note: RAPIER is listed 4 times (2 times in stored list), but this is different issue I think (related to its 2 modes of operation):
[screenshot from 2015-05-19 15 28 19](https://cloud.githubusercontent.com/assets/6692701/7702960/a4b4e036-fe3c-11e4-8fac-d31c0968c885.png)

**Comment by hvacengi** [comment]
I had to mess around with this when I fixed the engine thrust calculations.  I will go back and review to see if I also blocked the issue in listing engines.

**Comment by evg-zhabotinsky** [comment]
So, that's it!
My guess is that ModuleEnginesFX is (kind of) derived from ModuleEngines and thus gets listed twice:
* [Here](https://github.com/KSP-KOS/KOS/blob/a2e3fc8d67b86ccf01bc8ef545528aaaba82afad/src/kOS/Function/PrintList.cs#L207-L215) it causes engines to be listed twice and **is not fixed**
* And [there](https://github.com/KSP-KOS/KOS/blob/88992c05fbfdcd1ff0ea5f5b242447e1ec4a2331/src/kOS/Utilities/VesselUtils.cs#L114-L132) it counted engine twice when calculating maxthrust, and is already **fixed** in develop (**by ignoring ModuleEngineFX!?**).

Storing engine list to variable works fine [here](https://github.com/KSP-KOS/KOS/blob/2b72e618ce888bb8aad52be540fc86338b2b1870/src/kOS/Suffixed/Part/EngineValue.cs#L47-L58) because of "else".

**Comment by evg-zhabotinsky** [comment]
Can't test it myself because I don't know how to build the thing :(

**Comment by hvacengi** [comment]
The deal is that ModuleEngineFX didn't used to to inherit from ModuleEngine, and now it does.  So the "is ModuleEngine" returns true for both types now.  Technically, yes I think I ignore ModuleEngineFX for thrust, but I know for a fact that ModuleEngineAdapter is receiving objects typed as ModuleEngineFX, so I decided not to delete the reference entirely.

@erendrake is there a good reason for us to have the listing logic in two different locations like that, or should I look at referencing one method from the other so that we only need to change the code in one place?  Obviously the fast fix is to just edit the printed lists to be correct.
