### ISSUE TITLE
cooked controls go bonkers, depending on controlling part

### ISSUE THREAD

**Issue by Schnobs** [KSP-KOS/KOS#272]
Test case: a tricoupler with three pods on it., one kOS core (five parts total).
issue "lock steering to prograde." command.
Works as long as the first pod is the controlling part. If you control the vessel from any of the other two pods, the ship goes into a wild spin.

It doesn't matter which of the pods is manned: the one placed first is the one that works.

**Comment by erendrake** [comment]
I imagine this is fixed as no one is complaining about it :)

**Comment by Dunbaratu** [comment]
Uhhh... I saw complaints about it as recently as a month ago in the forum thread actually.  This is the "control from here" problem.  It may be fixed, but it's not that long ago that it was still an issue.

**Comment by erendrake** [comment]
Well damm

**Comment by Schnobs** [comment]
As of kOS 0.15.6.0, it still exists.

There's also a minor (possibly related) issue where even when controlling from the root part, the ship gets it's direction only almost right; it's constantly correcting for some last tiny bit, the effect looks like oversteering or wobbliness.

Having a docking port facing forward and controlling from there works fine most of the time, though. It solves both uncontrollable and "wobbly" vessels. Problem is that the port still needs to face in the same direction as the root part.

**Comment by akrasuski1** [comment]
Ugh, I've been having this problem yesterday too, so I guess this is still alive. In my case, it was a lifter ship meant to be reusable - so I had two probe cores in it - one from the lifter itself, and the other from the lifted ship. Initially, the root part was a fuel tank, and *any* `lock steering` command was putting me in a wild spin. The particular command I tested with, was: `lock steering to lookdirup(up:vector,ship:facing:upvector).`

Changing the root part to be the lifter's core fixed it.

**Comment by hvacengi** [comment]
Closed via #1118
