### ISSUE TITLE
ambiguous duplicate links in the RST docs files

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KOS#484]
These are some warnings that:
```
make clean
make html
```
generated in the docs that we probably need to fix, but I was only trying to update the docs to 0.15.5, not fix everything from before, so I just reported them and moved on.  Some minor things with markups I did on my own, but a lot of these were duplications of the same link term.  Fixing them requires thought on where sections of the docs should be moved to and I didn't want to do that unilaterally without discussion.

```
/Users/madings/KOS-1/doc/source/commands/flight/pilot.rst:10: WARNING: duplicate description of structure Control, other instance in /Users/madings/KOS-1/doc/source/commands/flight.rst
/Users/madings/KOS-1/doc/source/commands/flight/systems.rst:9: WARNING: duplicate description of global RCS, other instance in /Users/madings/KOS-1/doc/source/commands/flight.rst
/Users/madings/KOS-1/doc/source/commands/flight/systems.rst:17: WARNING: duplicate description of global SAS, other instance in /Users/madings/KOS-1/doc/source/commands/flight.rst
/Users/madings/KOS-1/doc/source/commands/flight/systems.rst:25: WARNING: duplicate description of global LIGHTS, other instance in /Users/madings/KOS-1/doc/source/commands/flight.rst
/Users/madings/KOS-1/doc/source/commands/flight/systems.rst:33: WARNING: duplicate description of global BRAKES, other instance in /Users/madings/KOS-1/doc/source/commands/flight.rst
/Users/madings/KOS-1/doc/source/commands/flight/systems.rst:41: WARNING: duplicate description of global TARGET, other instance in /Users/madings/KOS-1/doc/source/commands/flight.rst
/Users/madings/KOS-1/doc/source/commands/flight/warp.rst:5: WARNING: duplicate description of global WARP, other instance in /Users/madings/KOS-1/doc/source/commands/flight.rst
/Users/madings/KOS-1/doc/source/commands/flight/warp.rst:5: WARNING: duplicate description of global The :global:`WARP` global variable can be set to change the game warp to a value between 0 and 7::, other instance in /Users/madings/KOS-1/doc/source/commands/flight.rst
/Users/madings/KOS-1/doc/source/language/variables.rst:80: WARNING: duplicate label lock, other instance in /Users/madings/KOS-1/doc/source/language/flow.rst
/Users/madings/KOS-1/doc/source/math/basic.rst:3: WARNING: duplicate label math, other instance in /Users/madings/KOS-1/doc/source/math.rst
/Users/madings/KOS-1/doc/source/structures/maneuvering.rst:6: WARNING: toctree glob pattern u'maneuvering/*' didn't match any documents
/Users/madings/KOS-1/doc/source/structures/vessels/resource.rst:8: WARNING: duplicate description of structure Resource, other instance in /Users/madings/KOS-1/doc/source/structures/vessels/aggregateresource.rst
/Users/madings/KOS-1/doc/source/structures/vessels/resource.rst:35: WARNING: duplicate description of attribute Resource:NAME, other instance in /Users/madings/KOS-1/doc/source/structures/vessels/aggregateresource.rst
/Users/madings/KOS-1/doc/source/structures/vessels/resource.rst:42: WARNING: duplicate description of attribute Resource:AMOUNT, other instance in /Users/madings/KOS-1/doc/source/structures/vessels/aggregateresource.rst
/Users/madings/KOS-1/doc/source/structures/vessels/resource.rst:49: WARNING: duplicate description of attribute Resource:CAPACITY, other instance in /Users/madings/KOS-1/doc/source/structures/vessels/aggregateresource.rst
```

Those are all duplication complaints (meaning we have to re-arrange the layout and move some stuff together, probably), except for this one:

```
/Users/madings/KOS-1/doc/source/structures/maneuvering.rst:6: WARNING: toctree glob pattern u'maneuvering/*' didn't match any documents
```
There is a maneuvering.rst that refers to the directory maneuvering/, even though there is no directory maneuvering/ in the repository.

**Comment by theodoregoetz** [comment]
I'm going to try to eliminate all warnings and errors from the sphinx make process. Working on this now...

**Comment by theodoregoetz** [comment]
By the way, these "duplicates" are not actually duplicated in the source, just the generated html.

**Comment by erendrake** [comment]
@Dunbaratu I will let you confirm that this issue is resolved.

**Comment by Dunbaratu** [comment]
It will probably be a day or so before I can re-try the HTML generation to confirm this.

**Comment by Dunbaratu** [comment]
The first several duplicates I'd looked at originally from that report were actually in the RST files.  For example, there really were two different places in separate RST files that claimed themselves to be the link target of the ``LOCK`` label.

**Comment by Dunbaratu** [comment]
ancient issue.  closed.  There still exist a few ambiguities, but they're in places we want them - places where the same thing is mentioned in two different files for convenience.
